- name: Turn the server into both an app and database server.
  user: root

  hosts: comboservers

  vars:
    app_db_name: "ithacash"
    app_db_user: "ithacash_db_user"
    app_db_password: "{{ lookup('file', '../../../ithacash_dev/settings/secrets/PRODUCTION_DB_PASSWORD') }}"

    manage_path: /ithacash/production
    venv_path: /ithacash/virtualenv
    settings_dot_path: ithacash_dev.settings.production
    hendrix_opts: "--loud --http_port 8000 --settings {{settings_dot_path}} --log /ithacash/hendrix-twisted.log"
    app_user: nonroot
    app_group: appdeployer

  roles:
  - app
  - database
  - caching
