# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20151111_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='ithacashstaff',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ithacashstaff',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ithacashstaff',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
