# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20160120_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='ithacashstaff',
            name='confirmed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ithacashstaff',
            name='most_recent_confirmation_key',
            field=models.CharField(default='sadsad', max_length=255),
            preserve_default=False,
        ),
    ]
