# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 23:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20160120_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='ithacashstaff',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 20, 23, 28, 28, 112090, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
