- name: apt-get install postgres
  apt: pkg={{item}} state=installed update_cache=yes
  with_items:
      - build-essential
      - postgresql
      - libpq-dev
      - python-psycopg2

- name: copy the local pg_hba.conf
  template: src=pg_hba.conf dest=/tmp/pg_hba.conf mode=0644 owner=postgres group=postgres

- name: move the file to the right place
  shell: 'version=`ls`; mv /tmp/pg_hba.conf $version/main/pg_hba.conf chdir=/etc/postgresql/'

- name: create postgres user
  user: name=postgres comment="postgres user"

- name: create database {{app_db_name}}
  postgresql_db: name={{app_db_name}}

- name: ensure user has access to database
  postgresql_user: db={{app_db_name}} name={{app_db_user}} password={{app_db_password}} priv=ALL

- name: Add database backup script to cron
  cron:
    name: Dump, encrypt, and backup Ithacash database to Egnyte
    hour: 6
    minute: 0
    job: /ithacash/virtualenv/bin/python /ithacash/production/ops/ansible/playbooks/roles/database/templates/db_backup.py >> /var/log/ithacash_db_backup.log
