# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20151111_2028'),
        ('accounts', '0028_auto_20160115_2246'),
    ]

    operations = [
    ]
