# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 05:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20160120_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ithacashuser',
            name='username',
            field=models.CharField(default=None, help_text=b'Other Ithacash users can use this to pay you. Simpler is better.', max_length=120, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(b'^[0-9a-zA-Z]*$', b'Only letters and numbers are allowed')]),
        ),
    ]
