- name: Prepare to add PPA from URL
  apt: pkg={{item}} update_cache=yes state=latest
  with_items:
    - apt-transport-https

# Inspired by this doc: https://www.varnish-cache.org/installation/ubuntu
- name: Add Varnish PPA Key
  apt_key: url=https://repo.varnish-cache.org/GPG-key.txt state=present

- name: Add Varnish PPA
  apt_repository: repo='deb https://repo.varnish-cache.org/ubuntu/ precise varnish-4.0'

- name: Add stable nginx PPA
  apt_repository: repo='ppa:nginx/stable'

- name: Install Varnish and nginx
  apt: pkg={{item}} update_cache=yes state=latest
  with_items:
    - varnish
    - nginx

- name: Varnish params
  template:
    src: etc__default__varnish
    dest: /etc/default/varnish
    force: yes

- name: Varnish VCL
  template:
    src: etc__varnish__default.vcl
    dest: /etc/varnish/default.vcl
    force: yes

- name: Restart varnish
  service: name=varnish state=restarted
  sudo: yes

- name: Copy SSL creds
  synchronize: src=../../../ithacash_dev/settings/secrets/ssl dest=/ithacash

- name: Remove nginx default config
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Apply Ithacash nginx config
  template: src=nginx-{{ deployment_environment }}.j2 dest=/etc/nginx/sites-enabled/{{ deployment_environment }}

- name: Restart nginx
  service: name=nginx state=restarted
  sudo: yes
