---
- hosts: servers
  vars_files:
    - vars.yml

  tasks:
  - name: Checkout repo from gitlab
    sudo: yes
    sudo_user: "{{ app_user }}"
    git:
      repo: 'git@gitlab.ithacash.com:ithacash/ithacash.git'
      dest: /ithacash/{{ nickname }}
      version: "{{ branch }}"
      accept_hostkey: yes
      depth: 1
      force: yes
  
  - name: Migrations
    sudo: yes
    sudo_user: "{{ app_user }}"
    django_manage:
      settings: ithacash_dev.settings.production
      command: migrate
      virtualenv: /ithacash/virtualenv
      app_path: /ithacash/production
  
  - name: Apply hendrix upstart template
    template: src=hendrix-upstart.j2 dest=/etc/init/hendrix.conf mode=0751
    sudo: yes
    sudo_user: root
  
  - name: Start hendrix
    service:
      name="hendrix"
      state=restarted
    sudo: yes
    sudo_user: root
  
  - name: Copy SSL creds
    synchronize: src=../../../ithacash_dev/settings/secrets/ssl dest=/ithacash
  
  - name: Remove nginx default config
    file: path=/etc/nginx/sites-enabled/default state=absent
  
  - name: Apply Ithacash nginx config
    template: src=nginx-production.j2 dest=/etc/nginx/sites-enabled/production
    when: ansible_nodename == 'farva'
  
  - name: Apply staging.ithacash.com nginx config
    template: src=nginx-staging.js dest=/etc/nginx/sites-enabled/production
    when: ansible_nodename == 'Ithacacash.com'
  
  - name: Restart nginx
    service: name=nginx state=restarted
    sudo: yes  