---
- name: Configure Web Application Servers
  hosts: appservers
  remote_user: root

  vars:
    manage_path: /ithacash/production
    venv_path: /ithacash/virtualenv
    settings_dot_path: ithacash_dev.settings
    hendrix_opts: "--loud --http_port 8000 --settings {{settings_dot_path}} --log /ithacash/hendrix-twisted.log"
    user: nonroot
    group: appdeployer


  tasks:

    - name: Create appdeployers group
      group: name=appdeployer

    - name: Create non-root user to own repo and venv.
      user: name=nonroot group=appdeployer

    - name: Create /ithacash directory
      file: path=/ithacash state=directory owner=nonroot group=appdeployer

    - name: Add stable nginx PPA
      apt_repository: repo='ppa:nginx/stable'

    - name: Install OS requirements
      apt: pkg={{item}} update_cache=yes state=latest
      with_items:
        - build-essential
        - libpng12-dev
        - zlib1g-dev
        - libjpeg62-dev
        - python-dev
        - python-virtualenv
        - git-core
        - python2.7-dev
        - libffi-dev
        - libpq-dev
        - pkg-config
        - libgraphviz-dev
        - graphviz
        - libatlas-base-dev
        - libfreetype6-dev
        - postgresql-client
        - nginx

    - name: Copy project to server
      sudo: yes
      sudo_user: nonroot
      synchronize: src=../.. rsync_opts=--exclude=.*  dest=/ithacash/production mode=0644

    - name: Install Project reqs
      sudo: yes
      sudo_user: nonroot
      pip:
        requirements: /ithacash/production/requirements/requirements.txt
        virtualenv: /ithacash/virtualenv
        state: latest

    - name: Apply hendrix upstart template
      template: src=templates/hendrix-upstart.j2 dest=/etc/init/hendrix.conf mode=0751
      sudo: yes
      sudo_user: root

    - name: Start hendrix
      service:
        name="hendrix"
        state=restarted
      sudo: yes
      sudo_user: root

    - name: Copy SSL creds
      synchronize: src=../ssl dest=/ithacash

    - name: Remove nginx default config
      file: path=/etc/nginx/sites-enabled/default state=absent

    - name: Apply Ithacash nginx config
      template: src=templates/nginx-production.j2 dest=/etc/nginx/sites-enabled/production

    - name: Restart nginx
      service: name=nginx state=restarted
      sudo: yes


