---
- hosts: servers
  vars_files:
    - vars.yml
  sudo: true

  tasks:
  - name: Create appdeployers group
    group: name="{{ app_group }}"

  - name: Create non-root user to own repo and env
    user: name="{{ app_user }}" group="{{ app_group }}" generate_ssh_key=yes

  - name: Create /ithacash directory
    file: path=/ithacash state=directory owner="{{ app_user }}" group="{{ app_group }}"

  - name: Add stable nginx PPA
    apt_repository: repo='ppa:nginx/stable'

  - name: Install OS requirements
    apt: pkg={{item}} update_cache=yes state=latest
    with_items: {{ os_requirements }}