app_db_name: "ithacash"
app_db_user: "ithacash_db_user"
app_db_password: "{{ lookup('file', '../../../ithacash_dev/settings/secrets/PRODUCTION_DB_PASSWORD') }}"

manage_path: /ithacash/{{ nickname }}
venv_path: /ithacash/virtualenv
settings_dot_path: ithacash_dev.settings.{{ nickname }}
hendrix_opts: "--loud --http_port 8000 --settings {{settings_dot_path}} --log /ithacash/hendrix-twisted.log"
app_user: nonroot
app_group: appdeployer

project_repo: git@gitlab.ithacash.com:ithacash/ithacash.git
os_requirements:
    - build-essential
    - libpng12-dev
    - zlib1g-dev
    - libjpeg62-dev
    - python-dev
    - python-virtualenv
    - python-httplib2
    - git-core
    - python2.7-dev
    - libffi-dev
    - libpq-dev
    - pkg-config
    - libgraphviz-dev
    - graphviz
    - libatlas-base-dev
    - libfreetype6-dev
    - postgresql-client
    - nginx
    - postgresql-9.3
requirements_txt: "{{ manage_path }}/ops/ansible/playbooks/requirements.txt"