- name: Create appdeployers group
  group: name="{{ app_group }}"

- name: Create non-root user to own repo and venv.
  user: name="{{ app_user }}" group="{{ app_group }}" generate_ssh_key=yes

- name: Create /ithacash directory
  file: path=/ithacash state=directory owner="{{ app_user }}" group="{{ app_group }}"

- name: Install OS requirements
  apt: pkg={{item}} update_cache=yes state=latest
  with_items:
    - build-essential
    - libpng12-dev
    - zlib1g-dev
    - libjpeg62-dev
    - python-dev
    - python-virtualenv
    - python-httplib2
    - git-core
    - python2.7-dev
    - libffi-dev
    - libpq-dev
    - pkg-config
    - libgraphviz-dev
    - graphviz
    - libatlas-base-dev
    - libfreetype6-dev
    - postgresql-client
    - postgresql-9.3
    - cron
    - rsync

- name: slurp public key to use on gitlab
  slurp: src="~/.ssh/id_rsa.pub"
  register: appserver_ssh_key
  sudo_user: "{{ app_user }}"
  when: deployment_environment == 'production'

- name: Activate SSH key for gitlab 'appserver' user
  uri:
    url: https://gitlab.ithacash.com/api/v3/projects/1/keys
    method: POST
    HEADER_PRIVATE-TOKEN: '_utsQYTsABFiuheoCw9P'
    validate_certs: no
    body_format: raw
    body: "id=1&key={{appserver_ssh_key.content|b64decode|urlencode}}&title=Staging%20server%20key"
    status_code: 201
  when: deployment_environment == 'production'

- name: Checkout branch from gitlab
  sudo: yes
  sudo_user: "{{ app_user }}"
  git:
    repo: 'git@gitlab.ithacash.com:ithacash/ithacash.git'
    version: "{{ branch }}"
    dest: /ithacash/{{ deployment_environment }}
    accept_hostkey: yes
    depth: 1
    force: yes
  when: deployment_environment == 'production'

- name: Synchronize local repo
  sudo: yes
  sudo_user: "{{ app_user }}"
  synchronize:
      src: "{{ local_path }}/"
      dest: "{{ manage_path }}/../staging"
      rsync_opts:
        - "--exclude={{ local_path }}/.git"
  when: deployment_environment == 'staging'

- name: Install Project reqs
  sudo: yes
  sudo_user: "{{ app_user }}"
  pip:
    requirements: /ithacash/{{ deployment_environment }}/requirements/requirements.txt
    virtualenv: /ithacash/virtualenv
    state: latest

- name: Migrations
  sudo: yes
  sudo_user: "{{ app_user }}"
  django_manage:
<<<<<<< HEAD
    settings: ithacash.settings.{{ deployment_environment }}
=======
    settings: ithacash_dev.settings.{{ deployment_environment }}
>>>>>>> refs/remotes/origin/master
    command: migrate
    virtualenv: /ithacash/virtualenv
    app_path: /ithacash/{{ deployment_environment }}


- name: Apply hendrix upstart template
  template: src=hendrix-upstart.j2 dest=/etc/init/hendrix.conf mode=0751
  sudo: yes
  sudo_user: root

- name: Start hendrix
  service:
    name="hendrix"
    state=restarted
  sudo: yes
  sudo_user: root

- name: Add Django management scripts to cron
  cron:
    name: Send email with CSV of new Ithacash account signups for Cyclos import
    hour: 6
    minute: 0
<<<<<<< HEAD
    job: /ithacash/virtualenv/bin/python /ithacash/{{ deployment_environment }}/manage.py create_and_email_csv --settings=ithacash.settings.{{ deployment_environment }} >> /var/log/django_maintenance.log
=======
    job: /ithacash/virtualenv/bin/python /ithacash/{{ deployment_environment }}/manage.py create_and_email_csv --settings=ithacash_dev.settings.{{ deployment_environment }} >> /var/log/django_maintenance.log
<<<<<<< HEAD
>>>>>>> refs/remotes/origin/master
=======
  when: deployment_environment == 'production'
>>>>>>> develop
