- name: Create appdeployers group
  group: name="{{ app_group }}"

- name: Create non-root user to own repo and venv.
  user: name="{{ app_user }}" group="{{ app_group }}" generate_ssh_key=yes

- name: Create /ithacash directory
  file: path=/ithacash state=directory owner="{{ app_user }}" group="{{ app_group }}"

- name: Install OS requirements
  apt: pkg={{item}} update_cache=yes state=latest
  with_items:
    - build-essential
    - libpng12-dev
    - zlib1g-dev
    - libjpeg62-dev
    - python-dev
    - python-virtualenv
    - python-httplib2
    - git-core
    - python2.7-dev
    - libffi-dev
    - libpq-dev
    - pkg-config
    - libgraphviz-dev
    - graphviz
    - libatlas-base-dev
    - libfreetype6-dev
    - postgresql-client
    - postgresql-9.3
    - cron

## SSH key business not working; gitlab API seems whacky about it.
# - name: slurp public key to use on gitlab
#  slurp: src="~/.ssh/id_rsa.pub"
#  register: appserver_ssh_key
#  sudo_user: "{{ app_user }}"

# - name: Activate SSH key for gitlab 'appserver' user
#  uri:
#    url: https://gitlab.ithacash.com/api/v3/user/keys
#    method: POST
#    HEADER_PRIVATE-TOKEN: '1WDSfRcYyyg7sHikwFwd'
#    validate_certs: no
#    body_format: raw
#    body: "key={{appserver_ssh_key.content|b64decode}}&title=appserver_key"

- name: Checkout 'master' branch from gitlab
  sudo: yes
  sudo_user: "{{ app_user }}"
  git:
    repo: 'git@gitlab.ithacash.com:ithacash/ithacash.git'
    version: master
    dest: /ithacash/production
    accept_hostkey: yes
    depth: 1
    force: yes
  when: ansible_nodename == 'farva'

- name: Checkout 'develop' branch from gitlab
  sudo: yes
  sudo_user: "{{ app_user }}"
  git:
    repo: 'git@gitlab.ithacash.com:ithacash/ithacash.git'
    version: develop
    dest: /ithacash/production
    accept_hostkey: yes
    depth: 1
    force: yes
  when: ansible_nodename == 'Ithacacash.com'

- name: Install Project reqs
  sudo: yes
  sudo_user: "{{ app_user }}"
  pip:
    requirements: /ithacash/production/requirements/requirements.txt
    virtualenv: /ithacash/virtualenv
    state: latest

- name: Migrations
  sudo: yes
  sudo_user: "{{ app_user }}"
  django_manage:
    settings: ithacash_dev.settings.production
    command: migrate
    virtualenv: /ithacash/virtualenv
    app_path: /ithacash/production


- name: Apply hendrix upstart template
  template: src=hendrix-upstart.j2 dest=/etc/init/hendrix.conf mode=0751
  sudo: yes
  sudo_user: root

- name: Start hendrix
  service:
    name="hendrix"
    state=restarted
  sudo: yes
  sudo_user: root

- name: Apply cron jobs
  cron:
    name: Send email with CSV of new Ithacash account signups for Cyclos import
    hour: 8
    minute: 0
    job: /ithacash/virtualenv/bin/python /ithacash/production/manage.py create_and_email_csv >> /var/log/django_maintenance.log
